### ISSUE TITLE
I do not understand the installation instructions

### ISSUE THREAD

**Issue by worikgh** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#105]
`Download the code and open it in Xcode, archive the project and export the build. Easy, right?`

What is: `archive the project` in this context?

What is `export the build` in this context?

**Comment by worikgh** [comment]
I loaded the project into Xcode and then hit `run`.

**Comment by pschneider** [comment]
Hi, the idea is to sign the app with your own developer account, as it is not distributed otherwise. You can create the App binary by archiving using Xcode. This way you don't have to compile & run the app every time from Xcode.

To do that, just click on "Product" on the Xcode Menu Bar -> Archive and follow the steps.
