### ISSUE TITLE
Found which methods are slow. Now what? 

### ISSUE THREAD

**Issue by neokree** [RobertGummesson/BuildTimeAnalyzer-for-Xcode#66]
Hi, 

I have checked my project with this tool. My project is building in about 2 minutes and 30 seconds if clean.
My project is not so big, ~ 160 files with other pods. I want to make it a bit faster, like 30 sec or 1 minute. 
There are a list of things that can make the building faster (other than the ones in your posts on Medium)? If yes where I can find it?

**Comment by RobertGummesson** [comment]
Hi @neokree 

There's a lot that can be done and the first thing to do is to identify where the problem is. This is where the analyzer comes in. 

Outside of the Medium posts, I'm afraid I don't keep a list of tips, nor am I aware of anyone that does. In my case, it's mainly because all I have is my own experience. I would need to rely on community feedback to work out what the most common causes and workarounds are. The worst examples I've seen via Twitter and email has been where there's loads of Swift files being used (thousands) or when people use (abuse?) lazy getters.
